In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
df = pd.read_csv(r'Downloads/Titanic-Dataset.csv')

In [37]:
print(df.shape)         # how many rows, columns
print(df.info())        # column types + null counts
print(df.describe())    # stats summary

(891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [38]:

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
# Check nulls
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [40]:
# Age has ~177 nulls → fill with median
df['Age'].fillna(df['Age'].median(), inplace=True)

C:\Users\k9481\AppData\Local\Temp\ipykernel_7548\1430410866.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [41]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

C:\Users\k9481\AppData\Local\Temp\ipykernel_7548\3744086084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [32]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [43]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [44]:
df.drop(columns=["Name","Cabin","Ticket","PassengerId"],inplace=True)

In [35]:
df

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Cabin
0              1         0       3    male  22.0      1      0   NaN
1              2         1       1  female  38.0      1      0   C85
2              3         1       3  female  26.0      0      0   NaN
3              4         1       1  female  35.0      1      0  C123
4              5         0       3    male  35.0      0      0   NaN
..           ...       ...     ...     ...   ...    ...    ...   ...
886          887         0       2    male  27.0      0      0   NaN
887          888         1       1  female  19.0      0      0   B42
888          889         0       3  female  28.0      1      2   NaN
889          890         1       1    male  26.0      0      0  C148
890          891         0       3    male  32.0      0      0   NaN

[891 rows x 8 columns]

In [45]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [46]:
df["Sex"]=df["Sex"].map({'male':0,'female':1})

In [47]:
# Embarked: S→0, C→1, Q→2
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

In [48]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0
3         1       1    1  35.0      1      0  53.1000         0
4         0       3    0  35.0      0      0   8.0500         0

In [50]:
X=df.drop('Survived',axis=1)
y=df['Survived']

In [51]:
print(X.shape)  # should be (891, 7)
print(y.value_counts())  # check class balance

(891, 7)
Survived
0    549
1    342
Name: count, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [58]:
scalar=StandardScaler()

In [61]:
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [63]:
from sklearn.linear_model import LogisticRegression

In [64]:
model=LogisticRegression(max_iter=1000,random_state=42)

In [65]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [66]:
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, log_loss)

In [67]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

In [68]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Log Loss :", log_loss(y_test, y_prob))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy : 0.7988826815642458
Log Loss : 0.41568876206756655

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179


Confusion Matrix:
 [[89 16]
 [20 54]]

In [71]:
import numpy as np
# [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
# Example: 3rd class, male, 22 years, 1 sibling, 0 parents, 7.25 fare, S port
new_passenger = [[3, 0, 22, 1, 0, 7.25, 0]]

new_passenger_scaled = scalar.transform(new_passenger)

result = model.predict(new_passenger_scaled)
prob   = model.predict_proba(new_passenger_scaled)

print("Survived?" , "Yes" if result[0] == 1 else "No")
print("Probability:", prob[0][1])   # probability of survival

Survived? No
Probability: 0.09392801453110322

C:\Users\k9481\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [74]:
new_passenger = [[2, 1, 30, 1, 2, 17.25, 3]]

new_passenger_scaled = scalar.transform(new_passenger)

result = model.predict(new_passenger_scaled)
prob   = model.predict_proba(new_passenger_scaled)

print("Survived?" , "Yes" if result[0] == 1 else "No")
print("Probability:", prob[0][1])   # probability of survival

Survived? Yes
Probability: 0.833126998729556

C:\Users\k9481\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [76]:
import numpy as np

# get the raw z value before sigmoid
z = model.decision_function(scalar.transform([[3, 0, 22, 1, 0, 7.25, 0]]))
print("z value :", z)

# manually apply sigmoid
prob_manual = 1 / (1 + np.exp(-z))
print("Manual probability :", prob_manual)

# compare with predict_proba
print("Model probability  :", model.predict_proba(scalar.transform([[3, 0, 22, 1, 0, 7.25, 0]]))[0][1])

z value : [-2.26659007]
Manual probability : [0.09392801]
Model probability  : 0.09392801453110322

C:\Users\k9481\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\k9481\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [77]:
# Feature Importance — which feature matters most?
feature_names = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
importance = pd.Series(model.coef_[0], index=feature_names)
importance.abs().sort_values(ascending=False)

# See if Sex and Pclass come out on top — that would match real history ("women and children first").

Sex         1.270916
Pclass      0.804272
Age         0.404834
SibSp       0.359839
Fare        0.143666
Embarked    0.140339
Parch       0.089298
dtype: float64

In [78]:
#Try changing the threshold
# default is 0.5, try 0.4
threshold = 0.4
y_pred_custom = (y_prob[:, 1] >= threshold).astype(int)
print(classification_report(y_test, y_pred_custom))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       105
           1       0.75      0.82      0.79        74

    accuracy                           0.82       179
   macro avg       0.81      0.82      0.81       179
weighted avg       0.82      0.82      0.82       179